[project]
name = "call-me-maybe"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "romgutie", email = "romgutie@student.42nice.fr" }
]
requires-python = ">=3.10"
dependencies = [
    "llm-sdk",
    "numpy>=2.2.6",
    "pydantic>=2.13.4",
]

[tool.uv.workspace]
members = [
    "llm_sdk",
]

[tool.uv.sources]
llm-sdk = { workspace = true }
torch = [{ index = "pytorch-cpu" }]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[dependency-groups]
dev = [
    "flake8>=7.3.0",
    "mypy>=2.3.1",
]

[tool.mypy]
exclude = [
    "^\\.venv/",
    "^data/",
    "^test\\.py$",
]

[[tool.mypy.overrides]]
module = "llm_sdk.*"
ignore_errors = true
